# Start image with a node-based server
FROM node:18-alpine

# The /app dir should act as main app dir
WORKDIR /app 

# Copy App Package and Package-lock .json
COPY package*.json ./

# Copy local directories to docker image /app dir
COPY ./public ./public
COPY ./app ./app
COPY ./components ./components
COPY ./constants ./constants 

# Install NODE packages, install serve, build app and remove dependencies at the ned
RUN npm install \
    && npm install -g serve \
    && npm run build \
    && rm -fr node_modules 

EXPOSE 3030

# Start app using server cmd 
CMD ["serve", "-s", "build"]